### ISSUE TITLE
Plans to use accelerate?

### ISSUE THREAD

**Issue by rsamf** [TencentARC/Mix-of-Show#10]
The community has progressed to using huggingface accelerate due (I think) to its flexibility in user environments. Are there any plans to  switch to it? The module torch.distributed.launch is deprecated, and I would like to try out your code with 1 GPU.

**Comment by guyuchao** [comment]
Sure, I have developed the accelerate version in application branch. I plan to release it at the end of this month.

**Comment by rsamf** [comment]
Perfect! Thank you for a hasty response
