### ISSUE TITLE
what do the tokens <hina1> <hina2> <rand-0.13> mean and how can I set these

### ISSUE THREAD

**Issue by garychan22** [TencentARC/Mix-of-Show#11]
as descripted in the title, I am confused with these tokens in the default config

**Comment by guyuchao** [comment]
Sorry for late reply.

We use two token to represent a concept, similar to adjective+noun. So the first token usually inited by random embedding, the latter token is usually inited by the class of given subject.

If you want to use a new concept, just replace the <hina1> <hina2> to your concept name, for example, <potter1> <potter2>. Don't modify the <rand-0.13>, which is used to init the adjective token.

We also release the main branch for community, please try this branch for better performance.
