### ISSUE TITLE
regarding Step 1: Modify the Config

### ISSUE THREAD

**Issue by jakeyahn** [TencentARC/Mix-of-Show#12]
Im confuzed on amending or putting config file.

By tracking down the example character dataset, the text caption states something like '<TOK>, glasses, blurry background, blurry, upper body', and the train folder, I found the training config down in the training folder.

1. Where is exactly the config file located, when I want to amend the file?
   and should I amend the yml file or the json file?

2. according to the basic config you mentioned, there is only two TOKs, something like '<harry1>, <harry2>'. what is the two diferences between these two TOK?

Many thanks,

Jakey

**Comment by TalhaUsuf** [comment]
1. you need to create a json file for custom character pointing to the character images and captions:

```
[
{
"instance_prompt" : "<TOK>",
"instance_data_dir" : "path to folder having character images",
"caption_dir" : "path to folder having caption txt files"
}


]
```
then you need to create a **yaml file** , just copy paste following:

[](https://github.com/TencentARC/Mix-of-Show/blob/research_branch/options/train/EDLoRA/characters/real/EDLoRA_bengio_Cmix_B4_Iter1K.yml
)
change the base model if you want.
inside this you can see : "replace_mapping" which will replace the <TOK> from each of the caption files with the name you suggest like <abc1> <abc2>

pass this config to the training script.

**Comment by guyuchao** [comment]
Sorry for late reply.

We use two token to represent a concept, similar to adjective+noun. So the first token usually inited by random embedding, the latter token is usually inited by the class of given subject.

We released the application branch for community usage. Please try this branch for better performance.
