### ISSUE TITLE
大佬 你这个方式是需要训练2份LORA的意思吗？

### ISSUE THREAD

**Issue by Erwin11** [TencentARC/Mix-of-Show#14]
第一份lora是单个对象的lora，
第二份lora是上面多个lora的融合？

这个和kohya 的正则化训练多个角色相比有什么优势吗？ （目前我自己是没看到C站有多个角色的融合lora）

**Comment by guyuchao** [comment]
Sorry for late reply.

我们的方法不是训练两份lora。而是：1）第一步，对每个concept训练一份ED-LoRA，2）第二步，不需要数据，只需要多个单concept的ED-LoRA模型，我们将其融合，使得融合后的模型同时支持这些concept。

kohya的正则化训练多个角色我没有深入研究，但是通常同时训练难以保证同时得到每个concept的最好效果，并且得到的模型无法复用于和别的concept进行融合。
