### ISSUE TITLE
What is the Minimum VRAM requirement for Mix-of-Show?

### ISSUE THREAD

**Issue by Njasa2k** [TencentARC/Mix-of-Show#15]
What is the Minimum VRAM requirement for Mix-of-Show?

**Comment by guyuchao** [comment]
The minimum GPU memory is similar to kohya-ss LoRA, about 8-10GB to tune single concept (enable xformer, gradient checkpoint, batch=1 + gradient accumulation). For multi-concept fusion, it requires about 12GB. For multi-concept sampling with 1024*2048, it requires 6GB. Therefore, maybe 12 GB memory is the minimum requirement.
