### ISSUE TITLE
edlora visualization images quality

### ISSUE THREAD

**Issue by suchot** [TencentARC/Mix-of-Show#16]
Hello! Thanks for sharing the code and model!
when I used the readme code `accelerate launch train_edlora.py -opt options/train/EDLoRA/real/2101_EDLoRA_potter_Cmix_B4_Repeat250.yml
` generated corresponding visualization images. however,  this image can not reach the quality provided from Google Drive.  
Is there any configuration process missing?
<img width="1427" alt="image" src="https://github.com/TencentARC/Mix-of-Show/assets/24709446/b638af34-6769-469f-b8f6-b206affcb2b2">

**Comment by guyuchao** [comment]
Hi, I update the repo for performance improvement, and upload the test config and new checkpoint, please download and have a try. You should get lora alpha=0.7 of potter example as following:

![G_7 5_S_50---Iters-latest_Alpha-0 7](https://github.com/TencentARC/Mix-of-Show/assets/31696690/9ea30b47-997f-4be4-8475-587b10abeb95)

**Comment by suchot** [comment]
Thanks for your quick reply!   I got the comparable quality results. nice work, thx for sharing.
![G_7 5_S_50---Iters-latest_Alpha-0 7_newcode](https://github.com/TencentARC/Mix-of-Show/assets/24709446/71b7995f-c53b-4848-ab33-ce611e87aa6d)

PS:
https://github.com/TencentARC/Mix-of-Show/blob/ef74e12ff8fd952494908fe4cabf41f707d3ce52/README.md?plain=1#L115
```diff
  should change
- accelerate launch train_edlora.py -opt options/train/EDLoRA/real/2101_EDLoRA_potter_Cmix_B4_Repeat250.yml
+ accelerate launch train_edlora.py -opt options/train/EDLoRA/real/8101_EDLoRA_potter_Cmix_B4_Repeat500.yml
```

**Comment by guyuchao** [comment]
I have revised the README, thanks for point out.
