### ISSUE TITLE
Questions about vis_embedding

### ISSUE THREAD

**Issue by volcverse** [TencentARC/Mix-of-Show#2]
Hi! Thanks for sharing the great work!

I'm kind of a freshman in this area and I have studied your code for days. I feel confused about the vis_embedding in the code and it seems that there are no descriptions in the paper. （Sorry if I ignore them）So what's the vis_embedding actually is and what's the use of it?

Besides, what's the difference between negprompt and embedding_negprompt? 

Any response will be greatly appreciated! Again, thank you all for this great work!

**Comment by guyuchao** [comment]
Sorry for the late reply. We believe that LoRA only slightly adjusts the original weights (i.e., the meaning of low-rank), so the fine-tuned embeddings without LoRA weights should still contain sufficient identity information. Therefore, we visualize the fine-tuned embeddings using (1) pretrained model weights only and (2) pretrained model weights combined with tuned LoRA weights.

In scenario (1), we refer to the visualization as "xxx_embedding_negprompt," which displays your fine-tuned embeddings using only the pretrained model weights.

In scenario (2), we refer to the visualization as "xxx_negprompt," which represents the final results of your fine-tuned model, i.e., (embeddings and LoRA weights).

In the paper, the terms "Emb" and "Emb&LoRA" correspond to scenario (1) and scenario (2), respectively.

**Comment by volcverse** [comment]
> 

Very clear! Thank you so much!
