### ISSUE TITLE
Incorrect calculation of loss

### ISSUE THREAD

**Issue by miaopass** [TencentARC/Mix-of-Show#3]
https://github.com/TencentARC/Mix-of-Show/blob/27213c56b59afbc6023fb4645dfd9cf5610f60a7/mixofshow/archs/edlora_arch.py#L239

loss shape is [b, 4, 64, 64], mask shape is [b, 1, 64, 64]. This resulted in a fourfold increase in results.

**Comment by guyuchao** [comment]
Thanks for pointing out, this line is borrowed from Custom Diffusion (https://github.com/adobe-research/custom-diffusion/blob/main/src/diffusers_training.py#L984), I need to further check whether it has negative impact.
