### ISSUE TITLE
A confusion about the comment

### ISSUE THREAD

**Issue by Aziily** [TencentARC/Mix-of-Show#6]
I want to understand your model well, but when I read the code of gradient_fusion, I find a strange comment.

For example, the comment here [example](https://github.com/TencentARC/Mix-of-Show/blob/research_branch/scripts/mixofshow_scripts/Gradient_Fusion_EDLoRA.py#L482)

As far as I am concerned, the size of the tensor here should be changed along with the number of concepts should be added, but the comment means that it is a constant size. I wonder whether the comment here is wrong or I misunderstand the design here.

**Comment by guyuchao** [comment]
sorry，this comment is for my debug process. I haven't clean it. The size of the tensor indeed change along with the number of concepts
