### ISSUE TITLE
How does gradient fusion handle LoRas that share the same instant prompt?

### ISSUE THREAD

**Issue by levi** [TencentARC/Mix-of-Show#7]
Consider two LoRas that have been trained using the same instance prompt / unique token. What is the expected behavior when merging them via gradient fusion? Are their tokens changed or is there a problematic conflict?

**Comment by guyuchao** [comment]
Could you give a example. I don't understand this situation well. What is the meaning of "Consider two LoRas that have been trained using the same instance prompt / unique token".

Do you mean if I have two subjects, a specific dog, and a specific cat. Both are trained on with prompt "photo of a \<new1\> \<new2\>" individually, based on \<new1\> \<new2\> token?

**Comment by levi** [comment]
> Do you mean if I have two subjects, a specific dog, and a specific cat. Both are trained on with prompt "photo of a <new1> <new2>" individually, based on <new1> <new2> token?

Yes, that's correct.

**Comment by guyuchao** [comment]
This will not result in conflict at all. The token <new1> is just used to bind and use the new-learned embedding. In the concept merge process, we can assign any other tokens to represent that embedding, e.g. <new"n+1">, depending on how many concepts you want to merge. In the merged model, you can use that new token in the prompt.
