### ISSUE TITLE
Confusion about Table 1

### ISSUE THREAD

**Issue by Young98CN** [TencentARC/Mix-of-Show#9]
Hello! Great work! But, i have some questions about tab1. 
1. How were the data in Table 1 calculated and are there corresponding formulas? (It is clip score？)
2. What is the difference between Lower bound and Upper bound

**Comment by guyuchao** [comment]
1. The evaluation code and data is in (https://github.com/TencentARC/Mix-of-Show/tree/research_branch#straight_ruler-evaluation). We follow custom diffusion to compute text-alignment and image-alignment using CLIP Text or Image encoder. The Table 1 is the short summarize of detailed evaluation in Table 2.
2. The lower/upper bound means in customization, the highest text-alignment/lowest image-alignment is achieved by direct using class token without any tuning, e.g, using dog to replace <dogA> in pretrained stable diffusion.

**Comment by Young98CN** [comment]
Thx！
